import { useEffect, useState } from "react";
import { requestJson } from "../api";
import type { LoadRun } from "../load-testing";
import type { ServiceRecord } from "../types";
import { NoticeBanner, SectionCard, inputStyle, primaryButtonStyle, secondaryButtonStyle } from "../ui";
import { errorMessage, JsonEditor, JsonView, post, type Document } from "./common";

export function initialAssessment(service: ServiceRecord): Document {
  return { apiVersion: "chamber.ampule.dev/v1alpha1", kind: "ChamberConfig", service: { name: service.name, repo: "" }, deployment: { manifests: [], images: {}, workloads: [{ name: service.name, role: "target", kind: "Deployment" }], services: [{ name: service.name, port: 8080 }] }, traffic: { entrypoint: service.name, journeys: [{ name: "baseline", tool: "k6", method: "GET", path: "/health", expectedStatus: 200, requestEncoding: "none", stages: [{ duration: "30s", targetVus: 1 }, { duration: "5s", targetVus: 0 }] }] }, dependencies: { internal: [], external: [] }, runtime: { provider: "kubernetes", mode: "attach", kubernetesContext: "", namespace: "", cleanup: false, trafficAccess: { mode: "port-forward", service: service.name, servicePort: 8080 }, faults: [], requiredEnv: [], secretEnv: [], config: {} }, agents: { mode: "offline" } };
}
const sections = ["Target", "Scenario", "Traffic", "Performance", "Experiments", "Advanced"];
const suiteDefaults = { ratePerSecond: 1, durationSeconds: 60, maxInFlight: 16, timeoutSeconds: 30, warmupSeconds: 0, recoverySeconds: 10, recoveryRate: 1, windowSeconds: 30, failureWindows: 2, seed: 1, thresholds: { p95Ms: 500, maxErrorRate: 0.01, minCompletionRate: 0.99 } };
export function AssessmentBuilder({ base, service, isAdmin, onPlan }: { base: string; service: ServiceRecord; isAdmin: boolean; onPlan: (run: LoadRun) => void }) {
  const api = `${base}/chamber`;
  const [config, setConfig] = useState<Document>(() => initialAssessment(service));
  const [name, setName] = useState("Service assessment");
  const [section, setSection] = useState("Target");
  const [catalog, setCatalog] = useState<Document>({});
  const [targets, setTargets] = useState<Document[]>([]);
  const [scenarios, setScenarios] = useState<Document[]>([]);
  const [scenarioSearch, setScenarioSearch] = useState("");
  const [scenarioId, setScenarioId] = useState("");
  const [importText, setImportText] = useState("");
  const [goal, setGoal] = useState("");
  const [proposal, setProposal] = useState<Document | null>(null);
  const [discovery, setDiscovery] = useState<Document | null>(null);
  const [pendingScenario, setPendingScenario] = useState<{ normalized: Document; document?: Document } | null>(null);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [replace, setReplace] = useState(false);
  const [saveId, setSaveId] = useState("");
  useEffect(() => {
    let alive = true;
    void Promise.allSettled(["capabilities", "chambers", "scenarios"].map((kind) => requestJson<Document>(`${api}/catalog/${kind}`))).then(([capabilities, chambers, saved]) => {
      if (!alive) return;
      if (capabilities.status === "fulfilled") setCatalog(capabilities.value);
      if (chambers.status === "fulfilled") setTargets(chambers.value.chambers || []);
      if (saved.status === "fulfilled") setScenarios(saved.value.scenarios || []);
      const failure = [capabilities, chambers, saved].find((result) => result.status === "rejected");
      if (failure?.status === "rejected") setError(errorMessage(failure.reason));
    });
    return () => { alive = false; };
  }, [api]);
  async function perform(action: () => Promise<void>) {
    if (busy) return;
    setBusy(true); setError(""); setNotice("");
    try { await action(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); }
  }
  function update(area: string, field: string, value: unknown) { setConfig((old) => ({ ...old, [area]: { ...old[area], [field]: value } })); }
  function access(field: string, value: unknown) { setConfig((old) => ({ ...old, runtime: { ...old.runtime, trafficAccess: { ...old.runtime.trafficAccess, [field]: value } } })); }
  function targetName(value: string) {
    setConfig((old) => ({ ...old, service: { ...old.service, name: value }, deployment: { ...old.deployment, services: [{ name: value, port: old.runtime.trafficAccess?.servicePort || 8080 }] }, traffic: { ...old.traffic, entrypoint: value }, runtime: { ...old.runtime, trafficAccess: { ...old.runtime.trafficAccess, service: value } } }));
  }
  function applyScenario() {
    if (!pendingScenario) return;
    const normalized = pendingScenario.normalized;
    if (pendingScenario.document?.kind === "ChamberConfig") setConfig(pendingScenario.document);
    else setConfig((old) => ({ ...old, scenario: { ...normalized.identity, requiredSignals: normalized.requiredSignals || [], origin: normalized.origin }, traffic: { ...old.traffic, journeys: normalized.journeys || [], ...(normalized.load ? { load: normalized.load } : {}) }, agents: { ...old.agents, mode: normalized.agentMode || "offline", exclude: normalized.agentExclusions || [] } }));
    setName(normalized.identity?.name || name); setPendingScenario(null); setNotice("Scenario loaded. Review its target, schedules and any configured faults before planning.");
  }
  const runtime = config.runtime || {}, traffic = config.traffic || {}, journeys: Document[] = traffic.journeys || [];
  const kubernetes = runtime.provider === "kubernetes";
  const matchingScenario = scenarios.find((item) => `${item.source}/${item.id}` === scenarioId);
  const goals: Document[] = Array.isArray(catalog.goals) ? catalog.goals : [];
  const uploadSupported = (catalog.api_features || []).includes("managed_uploads");
  return <SectionCard title="Full Chamber assessment" subtitle="Build a complete assessment with targets, multiple journeys, performance gates, experiments and agents. Planning does not send traffic.">
    {error && <NoticeBanner tone="error">{error}</NoticeBanner>}{notice && <p role="status">{notice}</p>}
    <nav className="chamber-subnav" aria-label="Assessment configuration sections">{sections.map((item) => <button key={item} type="button" aria-current={section === item ? "step" : undefined} onClick={() => setSection(item)}>{item}</button>)}</nav>
    <fieldset className="load-form-fields" disabled={!isAdmin || busy}>
      {section === "Target" && <>
        <h3>Where will the assessment run?</h3><div className="chamber-form-grid">
          <label>Assessment name<input style={inputStyle} value={name} maxLength={120} onChange={(e) => setName(e.target.value)} /></label>
          <label>Execution environment<select style={inputStyle} value={kubernetes ? `kubernetes-${runtime.mode}` : "local"} onChange={(e) => { const local = e.target.value === "local"; setConfig((old) => { const next: Document = { ...old, runtime: { ...old.runtime, provider: local ? "docker" : "kubernetes", mode: local ? "local" : e.target.value.replace("kubernetes-", "") } }; delete next.chamber; return next; }); }}><option value="kubernetes-attach">Kubernetes · attach to existing workloads</option><option value="kubernetes-deploy">Kubernetes · deploy from repository</option><option value="local">Local · repository / Docker</option></select></label>
          {kubernetes && <label>Reusable target<select style={inputStyle} value={config.chamber?.id || ""} onChange={(e) => {
            const target = targets.find((item) => item.id === e.target.value);
            if (!target) { setConfig((old) => { const next = { ...old }; delete next.chamber; return next; }); return; }
            setConfig((old) => ({ ...old, chamber: { id: target.id }, service: { ...old.service, name: target.service }, deployment: { ...old.deployment, workloads: [{ name: target.workload, role: "target", kind: "Deployment" }], services: [{ name: target.service, port: old.runtime.trafficAccess?.servicePort || 8080 }] }, traffic: { ...old.traffic, entrypoint: target.service }, runtime: { ...old.runtime, provider: "kubernetes", mode: "attach", kubernetesContext: target.context, namespace: target.namespace, prometheusUrl: target.prometheus_url, trafficAccess: { mode: "port-forward", service: target.service, servicePort: old.runtime.trafficAccess?.servicePort || 8080 } } }));
          }}><option value="">Custom reviewed target</option>{targets.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.occupancy} · up to {item.max_vus} users</option>)}</select></label>}
          {kubernetes && <><label>Kubernetes context<input style={inputStyle} value={runtime.kubernetesContext || ""} onChange={(e) => update("runtime", "kubernetesContext", e.target.value)} /></label><label>Namespace<input style={inputStyle} value={runtime.namespace || runtime.namespaceBase || ""} onChange={(e) => update("runtime", "namespace", e.target.value)} /></label></>}
          <label>Target service<input style={inputStyle} value={config.service?.name || ""} onChange={(e) => targetName(e.target.value)} /></label>
          <label>Service port<input style={inputStyle} type="number" min={1} max={65535} value={runtime.trafficAccess?.servicePort || 8080} onChange={(e) => { access("servicePort", Number(e.target.value)); update("deployment", "services", [{ name: runtime.trafficAccess?.service || config.service.name, port: Number(e.target.value) }]); }} /></label>
          <label>Workload<input style={inputStyle} value={config.deployment?.workloads?.[0]?.name || ""} onChange={(e) => update("deployment", "workloads", [{ ...(config.deployment?.workloads?.[0] || {}), name: e.target.value, role: "target", kind: "Deployment" }])} /></label>
          <label>Prometheus URL<input style={inputStyle} value={runtime.prometheusUrl || ""} onChange={(e) => update("runtime", "prometheusUrl", e.target.value)} /></label>
          <label>Repository path on Chamber<input style={inputStyle} value={config.service?.repo || ""} onChange={(e) => update("service", "repo", e.target.value)} /></label>
        </div>
        <div className="studio-action-row"><button type="button" style={secondaryButtonStyle} disabled={!config.service?.repo} onClick={() => void perform(async () => { const inferred = await requestJson<Document>(`${api}/actions/inspect`, post({ repo: config.service.repo })); setConfig({ ...inferred, runtime: { ...runtime, ...inferred.runtime } }); setNotice("Repository inspected. Review inferred manifests, images, dependencies and request paths in Advanced."); })}>Inspect repository</button>
          {kubernetes && <button type="button" style={secondaryButtonStyle} disabled={!runtime.kubernetesContext || !runtime.namespace} onClick={() => void perform(async () => { setDiscovery(await requestJson(`${api}/actions/discover`, post({ context: runtime.kubernetesContext, namespace: runtime.namespace }))); setNotice("Discovery complete. Select the intended Service and workload; installed tools alone do not verify readiness."); })}>Discover namespace</button>}
        </div>
        {discovery && <><JsonView value={discovery} title="Discovered workloads, services and readiness" />{(discovery.services || []).map((item: Document) => <button type="button" key={item.name} style={secondaryButtonStyle} onClick={() => targetName(item.name)}>Use Service {item.name}</button>)}</>}
        <label><input type="checkbox" checked={Boolean(runtime.cleanup)} onChange={(e) => update("runtime", "cleanup", e.target.checked)} />Clean up deployed resources after execution</label>
        <p className="load-muted">Attach mode observes an existing workload. Deploy and local modes require the repository and runtime prerequisites on Chamber. Named target budgets and admission checks are enforced by Chamber.</p>
      </>}
      {section === "Scenario" && <>
        <h3>Choose a goal or reusable scenario</h3>
        <div className="chamber-form-grid"><label>Assessment goal<select style={inputStyle} value={goal} onChange={(e) => { setGoal(e.target.value); setProposal(null); }}><option value="">Choose a goal</option>{goals.map((item) => <option key={item.id || item.goal} value={item.id || item.goal}>{item.label || item.name}</option>)}</select></label>
          <button type="button" style={secondaryButtonStyle} disabled={!goal} onClick={() => void perform(async () => setProposal(await requestJson(`${api}/actions/propose`, post({ goal, service_name: config.service.name, workload_name: config.deployment.workloads?.[0]?.name || "", service_port: runtime.trafficAccess?.servicePort || 8080, request_path: journeys[0]?.path || "/health", repository_available: Boolean(config.service.repo), attach_mode: runtime.mode === "attach", discovery_complete: Boolean(discovery), telemetry_available: runtime.prometheusUrl ? ["prometheus"] : [] }))))}>Propose goal</button></div>
        {proposal && <div className="chamber-review"><h4>{proposal.label}</h4><p>{proposal.description}</p>{proposal.expectedOutcomes?.map((item: string) => <p key={item}>{item}</p>)}<JsonView value={{ assumptions: proposal.assumptions, missingInputs: proposal.missingInputs, requiredEvidence: proposal.requiredEvidence, safety: proposal.safety, request: proposal.requestPreview }} title="Proposal assumptions, missing inputs and required evidence" /><button type="button" style={secondaryButtonStyle} onClick={() => { update("traffic", "journeys", proposal.journeys); update("scenario", "requiredSignals", proposal.requiredEvidence); setNotice("Proposal traffic applied. Faults remain explicitly selected in Experiments."); }}>Apply proposal traffic</button></div>}
        <label>Search scenarios<input style={inputStyle} type="search" value={scenarioSearch} onChange={(e) => setScenarioSearch(e.target.value)} /></label>
        <label>Saved scenario<select style={inputStyle} value={scenarioId} onChange={(e) => { setScenarioId(e.target.value); setPendingScenario(null); }}><option value="">Choose a scenario</option>{scenarios.filter((item) => JSON.stringify(item).toLowerCase().includes(scenarioSearch.toLowerCase())).map((item) => <option key={`${item.source}/${item.id}`} value={`${item.source}/${item.id}`}>{item.name} · {item.trafficAdapters?.join(", ")} · {item.faults?.length ? "Faults configured" : "Observe only"}</option>)}</select></label>
        {matchingScenario && <div className="chamber-review"><p>{matchingScenario.description}</p><p>Revision {matchingScenario.revision} · {matchingScenario.journeyCount} journeys · {matchingScenario.expectedDuration}</p>{matchingScenario.warnings?.map((item: string) => <p key={item}>{item}</p>)}<button type="button" style={secondaryButtonStyle} onClick={() => void perform(async () => { const normalized = await requestJson<Document>(`${api}/scenarios/${scenarioId}`); let document: Document | undefined; if ((catalog.api_features || []).includes("scenario_document")) { const result = await requestJson<Document>(`${api}/scenarios/${scenarioId}/document`); document = result.document; } setPendingScenario({ normalized, document }); })}>Preview scenario compatibility</button></div>}
        <label>Import scenario YAML or JSON<textarea style={inputStyle} rows={6} value={importText} onChange={(e) => { setImportText(e.target.value); setPendingScenario(null); }} /></label>
        <label>Choose scenario file<input type="file" accept=".yaml,.yml,.json" onChange={(e) => { const file = e.target.files?.[0]; if (file) void perform(async () => { if (file.size > 256 * 1024) throw new Error("Scenario files must be under 256 KiB."); setImportText(await file.text()); }); }} /></label>
        <button type="button" style={secondaryButtonStyle} disabled={!importText.trim()} onClick={() => void perform(async () => { if ((catalog.api_features || []).includes("validate_document")) { const reply = await requestJson<Document>(`${api}/actions/validate-document`, post({ content: importText, service_name: config.service.name })); setPendingScenario({ normalized: reply.normalized, document: reply.document }); } else { const normalized = await requestJson<Document>(`${api}/actions/validate`, post({ content: importText, service_name: config.service.name })); setPendingScenario({ normalized }); } })}>Validate scenario</button>
        {pendingScenario && <div className="chamber-review"><h4>Compatibility review</h4><p>Target: {pendingScenario.normalized.targetService} · Port {pendingScenario.normalized.targetServicePort || "unspecified"}</p>{pendingScenario.normalized.warnings?.map((item: string) => <p key={item}>{item}</p>)}<p>Configured faults: {pendingScenario.normalized.configuredFaults?.join(", ") || "None"} · Revision {pendingScenario.normalized.revision}</p><JsonView value={pendingScenario.normalized} title="Scenario inputs and evidence requirements" /><button type="button" style={secondaryButtonStyle} onClick={applyScenario}>Load reviewed scenario</button></div>}
        <h4>Save this complete configuration for reuse</h4><label>Scenario ID<input style={inputStyle} value={saveId} maxLength={63} onChange={(e) => setSaveId(e.target.value)} placeholder="service-capacity-v1" /></label><label><input type="checkbox" checked={replace} onChange={(e) => setReplace(e.target.checked)} />Replace an existing user scenario with this ID</label>
        <button type="button" style={secondaryButtonStyle} disabled={!saveId} onClick={() => void perform(async () => { await requestJson(`${api}/actions/save-scenario`, post({ document: { ...config, scenario: { ...config.scenario, id: saveId, name } }, replace })); const saved = await requestJson<Document>(`${api}/catalog/scenarios`); setScenarios(saved.scenarios || []); setNotice("Complete scenario saved, including load, experiments and agent settings."); })}>Save reusable scenario</button>
      </>}
      {section === "Traffic" && <><h3>Traffic journeys</h3><p>Each journey keeps its own request and lifecycle. Shared load suites mix weighted HTTP and Relayna traffic.</p>{journeys.map((journey, index) => <JourneyEditor key={index} api={api} journey={journey} index={index} uploadSupported={uploadSupported} onChange={(next) => update("traffic", "journeys", journeys.map((old, i) => i === index ? next : old))} onRemove={() => update("traffic", "journeys", journeys.filter((_, i) => i !== index))} />)}<button type="button" style={secondaryButtonStyle} disabled={journeys.length >= 20} onClick={() => update("traffic", "journeys", [...journeys, { name: `journey-${journeys.length + 1}`, tool: "k6", method: "GET", path: "/health", expectedStatus: 200, requestEncoding: "none", stages: [{ duration: "30s", targetVus: 1 }] }])}>Add journey</button></>}
      {section === "Performance" && <><h3>Load delivery and performance gates</h3><label>Load model<select style={inputStyle} value={traffic.load?.model || "journeys"} onChange={(e) => { if (e.target.value === "journeys") { const next = { ...traffic }; delete next.load; setConfig((old) => ({ ...old, traffic: next })); } else update("traffic", "load", { ...suiteDefaults, ...traffic.load, model: e.target.value }); }}><option value="journeys">Journey users / iterations</option><option value="arrival">Arrival rate</option><option value="capacity">Capacity steps</option><option value="soak">Soak windows</option></select></label>
        {traffic.load && <><div className="chamber-form-grid">{([ ["ratePerSecond", "Arrivals per second", 0.1, 1000], ["durationSeconds", "Load duration seconds", 1, 3600], ["maxInFlight", "Maximum in-flight tasks", 1, 128], ["timeoutSeconds", "Request timeout seconds", 1, 300], ["warmupSeconds", "Warmup seconds", 0, 300], ["recoverySeconds", "Recovery seconds", 0, 300], ["windowSeconds", "Observation window seconds", 1, 300], ["failureWindows", "Consecutive failure windows", 1, 20] ] as const).map(([field, label, min, max]) => <label key={field}>{label}<input style={inputStyle} type="number" step={field === "ratePerSecond" ? "0.1" : "1"} min={min} max={max} value={traffic.load[field]} onChange={(e) => update("traffic", "load", { ...traffic.load, [field]: Number(e.target.value) })} /></label>)}</div><p className="load-muted">Capacity steps, datasets, weighted journeys, chained requests and phase-specific thresholds are preserved in advanced load options. Generator saturation produces an inconclusive assessment.</p><JsonEditor key={traffic.load.model} label="Advanced load options" value={traffic.load} onChange={(value) => update("traffic", "load", value)} /></>}
      </>}
      {section === "Experiments" && <><h3>Faults and recovery</h3><p>Faults are opt-in and require a second confirmation before execution. Chamber enforces target admission and setup checks.</p><label>Experiment family<select style={inputStyle} value={config.experiment?.family || ""} onChange={(e) => { setConfig((old) => { const next = { ...old }; if (!e.target.value) delete next.experiment; else next.experiment = { family: e.target.value, durationSeconds: 90, recoverySeconds: 30, pod: "" }; return next; }); }}><option value="">Traffic only</option>{Object.entries(catalog.experiment_families || {}).map(([key, label]) => <option key={key} value={key}>{String(label)}</option>)}</select></label>{config.experiment && <JsonEditor key={config.experiment.family} label="Experiment configuration" value={config.experiment} onChange={(value) => setConfig((old) => ({ ...old, experiment: value }))} />}<JsonEditor label="Legacy fault configuration" value={runtime.faults || []} onChange={(value) => update("runtime", "faults", value)} /></>}
      {section === "Advanced" && <><h3>Agents and complete configuration</h3><label>Agent mode<select style={inputStyle} value={config.agents?.mode || "offline"} onChange={(e) => update("agents", "mode", e.target.value)}><option value="offline">Offline deterministic</option><option value="off">Disabled</option><option value="live">Live OpenAI agents</option></select></label><JsonEditor label="Agent configuration" value={config.agents || {}} onChange={(value) => setConfig((old) => ({ ...old, agents: value }))} /><p className="load-muted">Use the complete configuration for manifests, image mappings, dependency settings, environment references, advanced lifecycle contracts and all other supported Chamber features. Apply edits before reviewing.</p><JsonEditor key={JSON.stringify(config)} label="Complete assessment configuration" value={config} onChange={(value) => { if (!["service", "deployment", "traffic", "runtime"].every((area) => value[area] && typeof value[area] === "object" && !Array.isArray(value[area])) || !Array.isArray(value.traffic.journeys) || !value.traffic.journeys.every((journey: unknown) => journey && typeof journey === "object" && !Array.isArray(journey))) throw new Error("Include service, deployment, traffic and runtime objects, with a traffic.journeys array of objects."); setConfig(value); }} /></>}
      <div className="chamber-builder-footer"><span>{journeys.length} journeys · {traffic.load?.model || "Journey schedule"} · {config.experiment?.family || (runtime.faults?.length ? "Legacy faults configured" : "Observe only")}</span><button type="button" style={primaryButtonStyle} disabled={!name.trim() || !journeys.length} onClick={() => void perform(async () => onPlan(await requestJson<LoadRun>(`${api}/plans`, post({ name, config, mode: kubernetes ? "kubernetes" : "local" }))))}>{busy ? "Preparing assessment…" : "Review assessment"}</button></div>
    </fieldset>
  </SectionCard>;
}

function JourneyEditor({ api, journey, index, uploadSupported, onChange, onRemove }: { api: string; journey: Document; index: number; uploadSupported: boolean; onChange: (journey: Document) => void; onRemove: () => void }) {
  const [field, setField] = useState("file");
  const [error, setError] = useState("");
  const [uploading, setUploading] = useState(false);
  function update(key: string, value: unknown) { onChange({ ...journey, [key]: value }); }
  return <details className="chamber-journey" open={index === 0}><summary>{journey.name} · {journey.adapter === "relayna" ? "Relayna task" : "HTTP"} · {journey.method} {journey.path}</summary><div className="chamber-form-grid">
    <label>Journey name<input style={inputStyle} value={journey.name || ""} onChange={(e) => update("name", e.target.value)} /></label><label>Traffic adapter<select style={inputStyle} value={journey.adapter === "relayna" ? "relayna" : "http"} onChange={(e) => { const next = { ...journey }; if (e.target.value === "relayna") { next.adapter = "relayna"; next.vus = 1; next.iterations = 1; next.durationSeconds = 30; next.relayna ||= { taskIdPath: "task_id", eventsPath: "/tasks/{task_id}/events", timeoutSeconds: 120 }; delete next.tool; delete next.stages; } else { delete next.adapter; delete next.relayna; delete next.vus; delete next.iterations; delete next.durationSeconds; next.tool = "k6"; next.stages = [{ duration: "30s", targetVus: 1 }]; } onChange(next); }}><option value="http">HTTP / k6</option><option value="relayna">Relayna lifecycle</option></select></label>
    <label>Request method<select style={inputStyle} value={journey.method || "GET"} onChange={(e) => update("method", e.target.value)}>{["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Request path<input style={inputStyle} value={journey.path || ""} onChange={(e) => update("path", e.target.value)} /></label><label>Expected status<input style={inputStyle} type="number" min={100} max={599} value={journey.expectedStatus || 200} onChange={(e) => update("expectedStatus", Number(e.target.value))} /></label><label>Request encoding<select style={inputStyle} value={journey.requestEncoding || "none"} onChange={(e) => update("requestEncoding", e.target.value)}>{["none", "json", "form", "multipart", "raw"].map((item) => <option key={item}>{item}</option>)}</select></label>
    {journey.adapter === "relayna" && ([ ["vus", "Task concurrency", 32], ["iterations", "Total task iterations", 1000], ["durationSeconds", "Scheduling window seconds", 3600] ] as const).map(([key, label, max]) => <label key={key}>{label}<input style={inputStyle} type="number" min={1} max={max} value={journey[key] || 1} onChange={(e) => update(key, Number(e.target.value))} /></label>)}
  </div>
    {journey.requestEncoding === "raw" ? <label>Journey {index + 1} raw request body<textarea style={inputStyle} rows={5} value={typeof journey.body === "string" ? journey.body : ""} onChange={(e) => update("body", e.target.value)} /></label> : <JsonEditor label={`Journey ${index + 1} ${journey.requestEncoding === "form" ? "form fields" : journey.requestEncoding === "multipart" ? "multipart fields" : "request body"}`} value={journey.requestEncoding === "form" ? journey.form || {} : journey.requestEncoding === "multipart" ? journey.multipart?.fields || {} : journey.body || {}} onChange={(value) => journey.requestEncoding === "form" ? update("form", value) : journey.requestEncoding === "multipart" ? update("multipart", { ...journey.multipart, fields: value }) : update("body", value)} />}<JsonEditor label={`Journey ${index + 1} headers`} value={journey.headers || {}} onChange={(value) => update("headers", value)} />
    {journey.adapter === "relayna" ? <JsonEditor label={`Journey ${index + 1} lifecycle`} value={journey.relayna || {}} onChange={(value) => update("relayna", value)} /> : <JsonEditor label={`Journey ${index + 1} traffic stages`} value={journey.stages || []} onChange={(value) => update("stages", value)} />}
    {journey.requestEncoding === "multipart" && <div className="chamber-review"><label>Multipart field name<input style={inputStyle} value={field} onChange={(e) => setField(e.target.value)} /></label><label>Upload test file<input type="file" disabled={uploading || !uploadSupported} onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; setUploading(true); setError(""); const form = new FormData(); form.set("field", field); form.set("file", file); void requestJson<Document>(`${api}/uploads`, { method: "POST", body: form }).then((result) => update("multipart", { ...journey.multipart, files: [...(journey.multipart?.files || []), result.file] }), (failure) => setError(errorMessage(failure))).finally(() => setUploading(false)); }} /></label><p>Up to 128 MiB per file and 256 MiB per plan. Uploaded files are stored on Chamber and signed for planning.</p>{!uploadSupported && <p>Upgrade Chamber to enable managed uploads.</p>}{error && <NoticeBanner tone="error">{error}</NoticeBanner>}{journey.multipart?.files?.map((file: Document, i: number) => <div key={i}>{file.field}: {file.filename}<button type="button" style={secondaryButtonStyle} onClick={() => update("multipart", { ...journey.multipart, files: journey.multipart.files.filter((_: unknown, at: number) => at !== i) })}>Remove file {i + 1}</button></div>)}</div>}
    <JsonEditor label={`Journey ${index + 1} advanced options`} value={journey} onChange={onChange} /><button type="button" style={secondaryButtonStyle} onClick={onRemove}>Remove journey {index + 1}</button>
  </details>;
}
