import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { requestJson } from "../api";
import type { LoadRun } from "../load-testing";
import { Link } from "../scoped-link";
import { NoticeBanner, SectionCard, formatTimestamp, inputStyle, primaryButtonStyle, secondaryButtonStyle } from "../ui";
import { errorMessage, JsonView, Pager, post, type Document } from "./common";

const tabs = ["Overview", "Tasks", "Timeline", "Findings", "Evidence", "Configuration", "Agents"];
export function RunResults({ base, serviceId, run, isAdmin, onPlan, onRefresh }: { base: string; serviceId: string; run: LoadRun | null; isAdmin: boolean; onPlan: (run: LoadRun) => void; onRefresh: () => void }) {
  const [params, setParams] = useSearchParams();
  const externalId = params.get("chamber_run") || "";
  const bound = externalId ? null : run;
  const id = externalId || bound?.chamber?.run_id || bound?.chamber?.plan_id || "";
  const reference = !externalId && run ? `reference=${encodeURIComponent(run.id)}` : "";
  const api = `${base}/chamber`, runApi = `${api}/runs/${encodeURIComponent(id)}`;
  const [data, setData] = useState<Document | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [revision, setRevision] = useState(0);
  const [tags, setTags] = useState("");
  const [baseline, setBaseline] = useState("");
  const [comparison, setComparison] = useState<Document | null>(null);
  const [cleanupConfirmed, setCleanupConfirmed] = useState(false);
  const tab = tabs.includes(params.get("result_tab") || "") ? params.get("result_tab")! : "Overview";
  useEffect(() => {
    let alive = true;
    setComparison(null); setCleanupConfirmed(false);
    if (id) void requestJson<Document>(`${runApi}?${reference}`).then((value) => { if (alive) { setData(value); setTags((value.run?.tags || []).join(", ")); setError(""); } }, (e) => { if (alive) setError(errorMessage(e)); });
    return () => { alive = false; };
  }, [runApi, reference, revision]);
  useEffect(() => { setData(null); }, [runApi, reference]);
  async function perform(action: () => Promise<void>) {
    setBusy(true); setError("");
    try { await action(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); }
  }
  function chooseTab(value: string) { setParams((old) => { const next = new URLSearchParams(old); next.set("result_tab", value); return next; }); }
  return <>
    <details className="chamber-history-disclosure" open={!id}><summary>Browse Chamber history</summary><ChamberHistory api={api} selected={id} onSelect={(value) => { setParams((old) => { const next = new URLSearchParams(old); next.set("chamber_run", value); next.set("result_tab", "Overview"); return next; }); }} /></details>
    {!id ? <SectionCard title="Assessment results"><p>Select a run from the Chamber history or your recent Studio plans.</p></SectionCard> : <SectionCard title="Assessment workspace" subtitle={`Chamber run ${id} · ${externalId ? "Chamber workspace history" : "Pinned to the reviewed Studio connection"}`}>
      {error && <NoticeBanner tone="error">{error}{data && " · Showing the last successful assessment snapshot."}</NoticeBanner>}
      <div className="studio-action-row"><button style={secondaryButtonStyle} onClick={() => setRevision((old) => old + 1)}>Refresh assessment</button>{["markdown", "json", "html"].map((format) => <a key={format} style={secondaryButtonStyle} href={`${api}/download/${encodeURIComponent(id)}/report?format=${format}&${reference}`} download>Download {format === "markdown" ? "Markdown" : format.toUpperCase()}</a>)}</div>
      <nav className="chamber-subnav" aria-label="Assessment result sections">{tabs.map((item) => <button key={item} onClick={() => chooseTab(item)} aria-current={item === tab ? "page" : undefined}>{item}</button>)}</nav>
      {!data ? <p role="status">{error ? "Assessment evidence is unavailable. Retry after checking the connection." : "Loading assessment evidence…"}</p> : <>
        {tab === "Overview" && <>
          <div className="chamber-verdict"><span className="chamber-badge">Execution: {bound?.state || data.run?.state || "unknown"}</span><h3>Assessment: {data.result?.status || "Awaiting assessment"}</h3><p>Completing execution does not establish readiness. The verdict depends on the collected evidence and the reviewed scope.</p></div>
          <dl className="chamber-facts"><div><dt>Readiness score</dt><dd>{data.result?.readiness_score ?? "Unavailable"}</dd></div><div><dt>Evidence coverage</dt><dd>{data.result?.evidence_coverage_percent == null ? "Unavailable" : `${data.result.evidence_coverage_percent}%`}</dd></div><div><dt>Conclusive</dt><dd>{data.result?.conclusive == null ? "Not reported" : data.result.conclusive ? "Yes" : "No"}</dd></div><div><dt>Confidence</dt><dd>{typeof data.result?.confidence === "string" ? data.result.confidence : "See assessment details"}</dd></div></dl>
          {(data.result?.limitations || []).map((item: string, i: number) => <NoticeBanner key={i} tone="info">{item}</NoticeBanner>)}
          <JsonView value={data.result || {}} title="Verdict, tested scope, evidence gaps and next actions" />{data.summary?.truncated_fields?.length > 0 && <NoticeBanner tone="info">Some rendered fields are bounded: {data.summary.truncated_fields.map((field: string | Document) => typeof field === "string" ? field : field.path || field.field || "Large field").join(", ")}. Download the full report or evidence for authoritative details.</NoticeBanner>}
          <JsonView value={data.relayna?.load || data.relayna?.load_summary || data.load || data.config?.traffic?.load || {}} title="Load delivery, performance gates and generator limits" />
          <JsonView value={data.result?.rollback || data.result?.cleanup || data.rollback || { cleanup_required: bound?.cleanup_required, rollback_verified: data.result?.rollback_verified }} title="Fault restoration and cleanup evidence" />
          <h4>Run identity and provenance</h4><dl className="chamber-facts"><div><dt>Studio reference</dt><dd>{bound?.id || data.metadata?.origin?.studio_reference || "Created outside this Studio service"}</dd></div><div><dt>Plan / execution</dt><dd>{bound?.chamber?.plan_id || "—"} / {id}</dd></div><div><dt>Job / connection</dt><dd>{bound?.chamber?.job_id || "—"} / {bound?.chamber?.connection_id || "Current connection"}</dd></div><div><dt>Studio retention</dt><dd>{bound?.expires_at ? formatTimestamp(bound.expires_at) : "No Studio reference"}</dd></div></dl><p className="load-muted">Studio references expire after 30 days. Chamber workspace history and evidence have separate retention.</p>
          {bound?.cleanup_required && !externalId && <div className="chamber-review"><h4>Target requires attention</h4><p>Restore any injected faults and inspect the workload and resources before releasing this target for another assessment.</p><label><input type="checkbox" checked={cleanupConfirmed} onChange={(e) => setCleanupConfirmed(e.target.checked)} />I verified fault restoration and cleanup on this target.</label><button style={primaryButtonStyle} disabled={!isAdmin || !cleanupConfirmed || busy} onClick={() => void perform(async () => { await requestJson(`${api}/jobs/${encodeURIComponent(bound?.chamber?.job_id || "")}/cleanup-verified?${reference}`, post({ confirmed: true })); setCleanupConfirmed(false); onRefresh(); setRevision((old) => old + 1); })}>Confirm cleanup verified</button></div>}
          <fieldset disabled={!isAdmin || busy} className="load-form-fields"><h4>Reuse and organize</h4><div className="studio-action-row"><button style={secondaryButtonStyle} onClick={() => void perform(async () => onPlan(await requestJson<LoadRun>(`${runApi}/rerun?${reference}`, post({}))))}>Prepare rerun for review</button><button style={secondaryButtonStyle} onClick={() => void perform(async () => { await requestJson(`${runApi}/archive?${reference}`, post({ archived: !data.run?.archived })); setRevision((old) => old + 1); })}>{data.run?.archived ? "Restore archived run" : "Archive run"}</button></div><label>Run tags<input style={inputStyle} value={tags} onChange={(e) => setTags(e.target.value)} placeholder="baseline, release-candidate" /></label><button style={secondaryButtonStyle} onClick={() => void perform(async () => { await requestJson(`${runApi}/tags?${reference}`, post({ tags: tags.split(",").map((value) => value.trim()).filter(Boolean) })); setRevision((old) => old + 1); })}>Save tags</button></fieldset>
          <h4>Compare against a baseline</h4><label>Baseline run ID<input style={inputStyle} value={baseline} onChange={(e) => { setBaseline(e.target.value); setComparison(null); }} /></label><button style={secondaryButtonStyle} disabled={!isAdmin || !baseline || baseline === id || busy} onClick={() => void perform(async () => setComparison(await requestJson(`${api}/actions/compare`, post({ baseline_run_id: baseline, candidate_run_id: id, reference: bound?.id }))))}>Compare runs</button>{comparison && <JsonView value={comparison} title="Baseline comparison, regressions and evidence alignment" />}
        </>}
        {tab === "Tasks" && <TaskEvidence api={runApi} reference={reference} serviceId={serviceId} />}
        {tab === "Timeline" && <><p>Lifecycle events and the bounded evidence timeline retain their source identities and correlation type.</p><EventList events={data.events || []} /><EvidenceExplorer api={runApi} reference={reference} /></>}
        {tab === "Findings" && <>{!data.findings?.length && <p>No findings have been reported. This does not imply a passing assessment.</p>}{data.findings?.map((finding: Document, i: number) => <article className="chamber-review" key={finding.finding_id || i}><span className="chamber-badge">{finding.severity || "info"} · {finding.signal_type || "assessment"}</span><h4>{finding.title || finding.finding_id}</h4><p>{finding.summary || finding.description}</p><JsonView value={finding} title="Finding evidence and recommended action" /><button style={secondaryButtonStyle} onClick={() => { setParams((old) => { const next = new URLSearchParams(old); next.set("result_tab", "Evidence"); next.set("finding", finding.finding_id || ""); return next; }); }}>Investigate cited evidence</button></article>)}</>}
        {tab === "Evidence" && <><EvidenceExplorer key={params.get("finding") || "all"} api={runApi} reference={reference} finding={params.get("finding") || ""} /><h4>Registered evidence artifacts</h4><p>Downloads are verified by Chamber against registered evidence and digests. Studio limits each artifact download to 32 MiB.</p>{!data.evidence?.length && <p>No artifacts are registered yet.</p>}{data.evidence?.map((item: Document, i: number) => <div className="chamber-review" key={item.evidence_id || i}><strong>{item.evidence_id || item.type}</strong><JsonView value={item} title="Artifact identity, coverage and digest" />{item.evidence_id && <a style={secondaryButtonStyle} download href={`${api}/download/${encodeURIComponent(id)}/evidence?evidence_id=${encodeURIComponent(item.evidence_id)}&${reference}`}>Download {item.evidence_id}</a>}</div>)}</>}
        {tab === "Configuration" && <><JsonView value={data.config} title="Reviewed configuration and full load settings" /><JsonView value={data.metadata?.origin || bound?.origin} title="Caller provenance" /><JsonView value={data.plan || data.run} title="Execution plan and state" /></>}
        {tab === "Agents" && <>{(!data.agents || !Object.keys(data.agents).length) && <p>No agent outputs are available. Check the configured mode and exclusions.</p>}{Array.isArray(data.agents) ? data.agents.map((agent: Document, i: number) => <JsonView key={i} value={agent} title={`${agent.name || agent.agent || `Agent ${i + 1}`} · ${agent.status || "Output"}`} />) : <JsonView value={data.agents || {}} title="Agent outputs, findings and run state" />}</>}
      </>}
    </SectionCard>}
  </>;
}

export function TaskEvidence({ api, reference, serviceId }: { api: string; reference: string; serviceId: string }) {
  const [data, setData] = useState<Document | null>(null), [error, setError] = useState("");
  const [search, setSearch] = useState(""), [status, setStatus] = useState(""), [failedFirst, setFailedFirst] = useState(true), [page, setPage] = useState(1);
  useEffect(() => { let alive = true; const query = new URLSearchParams({ page: String(page), page_size: "25", search, status, failed_first: String(failedFirst) }); void requestJson<Document>(`${api}/tasks?${query}&${reference}`).then((result) => { if (alive) { setData(result); setError(""); } }, (e) => { if (alive) setError(errorMessage(e)); }); return () => { alive = false; }; }, [api, reference, page, search, status, failedFirst]);
  return <><div className="chamber-form-grid"><label>Search exact task IDs<input style={inputStyle} value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></label><label>Task status<select style={inputStyle} value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{["completed", "failed", "cancelled", "timeout"].map((item) => <option key={item}>{item}</option>)}</select></label><label><input type="checkbox" checked={failedFirst} onChange={(e) => { setFailedFirst(e.target.checked); setPage(1); }} />Failed tasks first</label></div>{error && <NoticeBanner tone="error">{error}</NoticeBanner>}<p>{data?.total_count ?? "Loading"} matching tasks · exact run attribution</p><div className="chamber-table-scroll" tabIndex={0} aria-label="Run task evidence"><table><thead><tr><th>Task ID</th><th>Terminal status</th><th>Success</th><th>Duration</th><th>Investigate</th></tr></thead><tbody>{data?.items?.map((task: Document) => <tr key={task.task_id}><td><code>{task.task_id}</code></td><td>{task.terminal_status || "Pending"}</td><td>{task.success === true ? "Yes" : task.success === false ? "No" : "Pending"}</td><td>{task.total_duration_ms == null ? "Unavailable" : `${task.total_duration_ms} ms`}</td><td><Link to={`/tasks/${encodeURIComponent(serviceId)}/${encodeURIComponent(task.task_id)}`}>Open task</Link></td></tr>)}</tbody></table></div>{data && !data.items?.length && <p>No tasks match these filters.</p>}<Pager page={data?.pagination?.page || page} pages={data?.pagination?.total_pages || 1} onPage={setPage} /></>;
}
function EventList({ events }: { events: Document[] }) { return <div className="chamber-events">{!events.length && <p>No events reported in this window.</p>}{events.map((item, i) => <article key={item.event_id || i}><time>{formatTimestamp(item.timestamp || item.observed_at)}</time><strong>{item.event || item.signal || item.state || "Event"}</strong><p>{item.summary || item.message || ""}</p>{item.correlation && <small>{item.correlation} correlation · {item.source_identity?.evidence_id}</small>}<JsonView value={item} title="Event details" /></article>)}</div>; }
function EvidenceExplorer({ api, reference, finding = "" }: { api: string; reference: string; finding?: string }) {
  const [filters, setFilters] = useState<Record<string, string>>({ finding }), [page, setPage] = useState(1), [data, setData] = useState<Document | null>(null), [error, setError] = useState("");
  useEffect(() => { let alive = true; const query = new URLSearchParams({ ...filters, page: String(page), page_size: "25" }); void requestJson<Document>(`${api}/evidence-explorer?${query}&${reference}`).then((result) => { if (alive) { setData(result); setError(""); } }, (e) => { if (alive) setError(errorMessage(e)); }); return () => { alive = false; }; }, [api, reference, filters, page]);
  return <div><h4>Correlated evidence explorer</h4><div className="chamber-form-grid">{["journey", "workload", "pod", "task_id", "signal", "severity"].map((field) => <label key={field}>{field.replace(/_/g, " ")}<select style={inputStyle} value={filters[field] || ""} onChange={(e) => { setFilters({ ...filters, [field]: e.target.value }); setPage(1); }}><option value="">All</option>{data?.facets?.[field]?.map((value: string) => <option key={value}>{value}</option>)}</select></label>)}{["start", "end"].map((field) => <label key={field}>{field === "start" ? "Evidence from (ISO time)" : "Evidence to (ISO time)"}<input style={inputStyle} value={filters[field] || ""} onChange={(e) => { setFilters({ ...filters, [field]: e.target.value }); setPage(1); }} /></label>)}</div>{finding && <p>Finding context: {finding} <button style={secondaryButtonStyle} onClick={() => setFilters({ ...filters, finding: "" })}>Clear finding context</button></p>}<p>{data?.pagination?.total_items ?? "Loading"} matching events · {data?.source_event_count ?? "—"} source events · {data?.truncated ? "Projection is bounded" : "No projection truncation reported"}</p>{error && <NoticeBanner tone="error">{error}</NoticeBanner>}<EventList events={data?.events || []} /><Pager page={data?.pagination?.page || page} pages={data?.pagination?.total_pages || 1} onPage={setPage} /><JsonView value={data?.correlation_legend || {}} title="Exact, run-window and inferred correlation" /></div>;
}
function ChamberHistory({ api, selected, onSelect }: { api: string; selected: string; onSelect: (id: string) => void }) {
  const [filters, setFilters] = useState<Record<string, string>>({}), [page, setPage] = useState(1), [data, setData] = useState<Document | null>(null), [error, setError] = useState("");
  useEffect(() => { let alive = true; void requestJson<Document>(`${api}/runs?${new URLSearchParams({ ...filters, page: String(page), page_size: "10" })}`).then((result) => { if (alive) { setData(result); setError(""); } }, (e) => { if (alive) setError(errorMessage(e)); }); return () => { alive = false; }; }, [api, filters, page]);
  return <SectionCard title="Chamber history" subtitle="Durable workspace runs across Chamber targets. Studio references and Chamber retention are independent."><div className="chamber-form-grid"><label>Search runs<input style={inputStyle} type="search" value={filters.q || ""} onChange={(e) => { setFilters({ ...filters, q: e.target.value }); setPage(1); }} /></label>{["state", "outcome", "environment", "fault"].map((field) => <label key={field}>{field}<select style={inputStyle} value={filters[field] || ""} onChange={(e) => { setFilters({ ...filters, [field]: e.target.value }); setPage(1); }}><option value="">All</option>{data?.facets?.[field === "outcome" ? "outcomes" : `${field}s`]?.map((item: string) => <option key={item}>{item}</option>)}</select></label>)}<label>Coverage<select style={inputStyle} value={filters.coverage || ""} onChange={(e) => { setFilters({ ...filters, coverage: e.target.value }); setPage(1); }}><option value="">All</option><option value="complete">Complete</option><option value="partial">Partial</option><option value="missing">Missing</option></select></label>{["date_from", "date_to"].map((field) => <label key={field}>{field === "date_from" ? "Created from" : "Created to"}<input style={inputStyle} type="date" value={filters[field] || ""} onChange={(e) => { setFilters({ ...filters, [field]: e.target.value }); setPage(1); }} /></label>)}<label><input type="checkbox" checked={filters.archived === "true"} onChange={(e) => { setFilters({ ...filters, archived: String(e.target.checked) }); setPage(1); }} />Include archived runs</label></div>{error && <NoticeBanner tone="error">{error}</NoticeBanner>}<div className="chamber-history-grid">{data?.runs?.map((item: Document) => <button className="load-history-item" aria-current={item.run_id === selected ? "true" : undefined} key={item.run_id} onClick={() => onSelect(item.run_id)}><strong>{item.service_name}</strong><span>{item.status || item.state} · {item.run_id}</span><small>{formatTimestamp(item.created_at)} · {item.environment}</small></button>)}</div>{data && !data.runs?.length && <p>No runs match these filters.</p>}{data?.partial_index && <p>The workspace index is bounded to the most recent 1,000 runs.</p>}<Pager page={data?.pagination?.page || page} pages={data?.pagination?.total_pages || 1} onPage={setPage} /></SectionCard>;
}
