import { useEffect, useState } from "react";
import { requestJson } from "../api";
import { NoticeBanner, SectionCard, inputStyle, primaryButtonStyle } from "../ui";
import { errorMessage, JsonView, post, type Document } from "./common";

export function TargetProfiles({ base, isAdmin }: { base: string; isAdmin: boolean }) {
  const api = `${base}/chamber`;
  const [targets, setTargets] = useState<Document[]>([]), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [profile, setProfile] = useState<Document>({ name: "", context: "", namespace: "", service: "", workload: "", prometheus_url: "", max_vus: 25, max_duration_seconds: 300, allow_faults: false, chaos_mesh: false });
  const [revision, setRevision] = useState(0);
  useEffect(() => { let alive = true; void requestJson<Document>(`${api}/catalog/chambers`).then((data) => { if (alive) { setTargets(data.chambers || []); setError(""); } }, (e) => { if (alive) setError(errorMessage(e)); }); return () => { alive = false; }; }, [api, revision]);
  return <SectionCard title="Reusable assessment targets" subtitle="Named targets bind a cluster, namespace and workload to admission budgets. Readiness is checked independently.">{error && <NoticeBanner tone="error">{error}</NoticeBanner>}
    <div className="chamber-history-grid">{targets.map((item) => <article className="chamber-review" key={item.id}><strong>{item.name}</strong><p>{item.context} · {item.namespace}</p><p>{item.service} / {item.workload} · {item.occupancy}</p><p>Up to {item.max_vus} users · {item.max_duration_seconds}s · {item.allow_faults ? "Faults allowed" : "Observe only"}</p><p>Target readiness: {item.readiness || "Not checked"}</p><button type="button" onClick={() => { const { id: _id, revision: _revision, jobs: _jobs, occupancy: _occupancy, attention_jobs: _attention, readiness: _readiness, ...values } = item; setProfile({ ...values, name: `${item.name} copy` }); }}>Clone target settings</button><JsonView value={item.attention_jobs || []} title="Jobs requiring cleanup attention" />{isAdmin && (item.attention_jobs || []).filter((job: Document) => job.job_id).map((job: Document) => <CleanupAttention key={job.job_id} api={api} job={job} onVerified={() => setRevision((old) => old + 1)} />)}</article>)}</div>
    {!targets.length && <p>No reusable targets are configured yet.</p>}
    {isAdmin && <form onSubmit={(e) => { e.preventDefault(); setBusy(true); setError(""); void requestJson(`${api}/actions/create-chamber`, post(profile)).then(() => { setRevision((old) => old + 1); setProfile((old) => ({ ...old, name: "" })); }, (failure) => setError(errorMessage(failure))).finally(() => setBusy(false)); }}><fieldset className="load-form-fields" disabled={busy}><h3>Create a reusable target</h3><div className="chamber-form-grid">{([ ["name", "Target name"], ["context", "Cluster context"], ["namespace", "Target namespace"], ["service", "Target Service"], ["workload", "Target workload"], ["prometheus_url", "Target Prometheus URL"] ] as const).map(([field, label]) => <label key={field}>{label}<input style={inputStyle} required={field !== "prometheus_url"} maxLength={field === "name" ? 100 : 200} value={profile[field]} onChange={(e) => setProfile({ ...profile, [field]: e.target.value })} /></label>)}<label>Maximum users<input style={inputStyle} type="number" min={1} max={100} value={profile.max_vus} onChange={(e) => setProfile({ ...profile, max_vus: Number(e.target.value) })} /></label><label>Maximum duration seconds<input style={inputStyle} type="number" min={20} max={7200} value={profile.max_duration_seconds} onChange={(e) => setProfile({ ...profile, max_duration_seconds: Number(e.target.value) })} /></label></div><label><input type="checkbox" checked={profile.allow_faults} onChange={(e) => setProfile({ ...profile, allow_faults: e.target.checked })} />Allow explicitly selected faults within this target</label><label><input type="checkbox" checked={profile.chaos_mesh} onChange={(e) => setProfile({ ...profile, chaos_mesh: e.target.checked })} />Chaos Mesh is configured for this target</label><button type="submit" style={primaryButtonStyle}>{busy ? "Saving target…" : "Save reusable target"}</button></fieldset></form>}
  </SectionCard>;
}

function CleanupAttention({ api, job, onVerified }: { api: string; job: Document; onVerified: () => void }) {
  const [confirmed, setConfirmed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  return <div className="chamber-review"><strong>Cleanup attention · {job.job_id}</strong><p>Restore injected faults and inspect target resources before releasing admission.</p><label><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />I verified fault restoration and cleanup for this job.</label><button type="button" style={primaryButtonStyle} disabled={!confirmed || busy} onClick={() => { setBusy(true); setError(""); void requestJson(`${api}/jobs/${encodeURIComponent(job.job_id)}/cleanup-verified`, post({ confirmed: true })).then(onVerified, (failure) => setError(errorMessage(failure))).finally(() => setBusy(false)); }}>Confirm job cleanup verified</button>{error && <NoticeBanner tone="error">{error}</NoticeBanner>}</div>;
}
