"""Create Studio PostgreSQL persistence.

Revision ID: 0001_studio_postgres
Revises:
Create Date: 2026-08-19 19:12:01.160104
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_studio_postgres"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "studio_members",
        sa.Column("user_id", sa.String(length=600), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("object_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_sign_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('admin', 'readonly')", name=op.f("ck_studio_members_member_role")),
        sa.CheckConstraint("status IN ('pending', 'active', 'blocked')", name=op.f("ck_studio_members_member_status")),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_studio_members")),
        sa.UniqueConstraint("tenant_id", "object_id", name="uq_studio_members_tenant_object"),
    )
    op.create_index("ix_studio_members_email", "studio_members", ["email"], unique=False)
    op.create_index("ix_studio_members_status_role", "studio_members", ["status", "role"], unique=False)
    op.create_table(
        "studio_notification_batches",
        sa.Column("batch_key", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "items", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("batch_key", name=op.f("pk_studio_notification_batches")),
    )
    op.create_table(
        "studio_notification_deliveries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("failure_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedupe_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studio_notification_deliveries")),
        sa.UniqueConstraint("service_id", "failure_id", name="uq_studio_notification_service_failure"),
    )
    op.create_index(
        "ix_studio_notification_retention", "studio_notification_deliveries", ["dedupe_expires_at"], unique=False
    )
    op.create_index(
        "ix_studio_notification_state_created", "studio_notification_deliveries", ["state", "created_at"], unique=False
    )
    op.create_table(
        "studio_operator_audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_user_id", sa.String(length=600), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=128), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studio_operator_audit_log")),
    )
    op.create_index(
        "ix_studio_audit_actor_time",
        "studio_operator_audit_log",
        ["actor_user_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_audit_action_time",
        "studio_operator_audit_log",
        ["action", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_audit_target_time",
        "studio_operator_audit_log",
        ["target_type", "target_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_audit_time", "studio_operator_audit_log", [sa.literal_column("occurred_at DESC")], unique=False
    )
    op.create_table(
        "studio_operator_settings",
        sa.Column("setting_key", sa.String(length=255), nullable=False),
        sa.Column(
            "value", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_by", sa.String(length=600), nullable=True),
        sa.PrimaryKeyConstraint("setting_key", name=op.f("pk_studio_operator_settings")),
    )
    op.create_table(
        "studio_outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studio_outbox")),
        sa.UniqueConstraint("channel", "dedupe_key", name="uq_studio_outbox_channel_dedupe"),
    )
    op.create_index(
        "ix_studio_outbox_pending",
        "studio_outbox",
        ["available_at", "id"],
        unique=False,
        postgresql_where=sa.text("delivered_at IS NULL"),
    )
    op.create_index(
        "ix_studio_outbox_delivered_retention",
        "studio_outbox",
        ["delivered_at"],
        unique=False,
        postgresql_where=sa.text("delivered_at IS NOT NULL"),
    )
    op.create_table(
        "studio_redis_imports",
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "counts", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("source_fingerprint", name=op.f("pk_studio_redis_imports")),
    )
    op.create_table(
        "studio_services",
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("environment", sa.String(length=128), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("auth_mode", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "capabilities", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "log_config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "metrics_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "trace_config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("service_id", name=op.f("pk_studio_services")),
    )
    op.create_index("ix_studio_services_base_url", "studio_services", ["base_url"], unique=False)
    op.create_index("ix_studio_services_environment_status", "studio_services", ["environment", "status"], unique=False)
    op.create_index(
        "uq_studio_services_active_environment_base_url",
        "studio_services",
        ["environment", "base_url"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "studio_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("ingest_method", sa.String(length=32), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("out_of_order", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("source_kind", sa.String(length=64), nullable=False),
        sa.Column("component", sa.String(length=255), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_timestamp_text", sa.Text(), nullable=True),
        sa.Column("event_id", sa.String(length=255), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column("parent_task_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=128), nullable=True),
        sa.Column("stage", sa.String(length=128), nullable=True),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["studio_services.service_id"],
            name=op.f("fk_studio_events_service_id_studio_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studio_events")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_studio_events_dedupe_key")),
    )
    op.create_index(
        "ix_studio_events_correlation_time",
        "studio_events",
        ["correlation_id", sa.literal_column("event_timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_events_retention",
        "studio_events",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.create_index(
        "ix_studio_events_service_task_time",
        "studio_events",
        ["service_id", "task_id", sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_events_service_effective_time",
        "studio_events",
        ["service_id", sa.text("COALESCE(event_timestamp, ingested_at) DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_events_task_effective_time",
        "studio_events",
        [
            "service_id",
            "task_id",
            sa.text("COALESCE(event_timestamp, ingested_at) DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "ix_studio_events_service_time",
        "studio_events",
        ["service_id", sa.literal_column("event_timestamp DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_events_status_stage_time",
        "studio_events",
        ["status", "stage", sa.literal_column("event_timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "uq_studio_events_service_source_event_id",
        "studio_events",
        ["service_id", "source_kind", "event_id"],
        unique=True,
        postgresql_where=sa.text("event_id IS NOT NULL"),
    )
    op.create_table(
        "studio_pull_ingestion_cursors",
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["studio_services.service_id"],
            name=op.f("fk_studio_pull_ingestion_cursors_service_id_studio_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("service_id", name=op.f("pk_studio_pull_ingestion_cursors")),
    )
    op.create_table(
        "studio_service_health_current",
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("overall_status", sa.String(length=32), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "document", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["studio_services.service_id"],
            name=op.f("fk_studio_service_health_current_service_id_studio_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("service_id", name=op.f("pk_studio_service_health_current")),
    )
    op.create_index(
        "ix_studio_health_current_status",
        "studio_service_health_current",
        ["overall_status", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_table(
        "studio_service_health_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("overall_status", sa.String(length=32), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "document", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["studio_services.service_id"],
            name=op.f("fk_studio_service_health_history_service_id_studio_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studio_service_health_history")),
    )
    op.create_index(
        "ix_studio_health_history_service_time",
        "studio_service_health_history",
        ["service_id", sa.literal_column("checked_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_health_history_status_time",
        "studio_service_health_history",
        ["overall_status", sa.literal_column("checked_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_health_history_retention",
        "studio_service_health_history",
        ["checked_at"],
        unique=False,
    )
    op.create_table(
        "studio_service_search_projections",
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("environment", sa.String(length=128), nullable=False),
        sa.Column(
            "tags", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("health_status", sa.String(length=32), nullable=True),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("auth_mode", sa.String(length=64), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["studio_services.service_id"],
            name=op.f("fk_studio_service_search_projections_service_id_studio_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("service_id", name=op.f("pk_studio_service_search_projections")),
    )
    op.create_index(
        "ix_studio_service_search_filters",
        "studio_service_search_projections",
        ["environment", "status", "health_status"],
        unique=False,
    )
    op.create_index(
        "ix_studio_service_search_tags_gin",
        "studio_service_search_projections",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "studio_task_search_projections",
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("environment", sa.String(length=128), nullable=False),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=128), nullable=True),
        sa.Column("stage", sa.String(length=128), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_event_type", sa.String(length=128), nullable=True),
        sa.Column("latest_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail_path", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["studio_services.service_id"],
            name=op.f("fk_studio_task_search_projections_service_id_studio_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("service_id", "task_id", name=op.f("pk_studio_task_search_projections")),
    )
    op.create_index("ix_studio_tasks_correlation", "studio_task_search_projections", ["correlation_id"], unique=False)
    op.create_index(
        "ix_studio_tasks_retention",
        "studio_task_search_projections",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.create_index(
        "ix_studio_tasks_service_last_seen",
        "studio_task_search_projections",
        ["service_id", sa.literal_column("last_seen_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_studio_tasks_status_stage_time",
        "studio_task_search_projections",
        ["status", "stage", sa.literal_column("last_seen_at DESC")],
        unique=False,
    )
    op.create_index("ix_studio_tasks_task", "studio_task_search_projections", ["task_id"], unique=False)
    op.execute(
        """
        CREATE FUNCTION relayna_studio_reject_audit_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'studio_operator_audit_log is append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER studio_operator_audit_log_append_only
        BEFORE UPDATE OR DELETE ON studio_operator_audit_log
        FOR EACH ROW EXECUTE FUNCTION relayna_studio_reject_audit_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER studio_operator_audit_log_append_only ON studio_operator_audit_log")
    op.execute("DROP FUNCTION relayna_studio_reject_audit_mutation()")
    op.drop_index("ix_studio_tasks_task", table_name="studio_task_search_projections")
    op.drop_index("ix_studio_tasks_status_stage_time", table_name="studio_task_search_projections")
    op.drop_index("ix_studio_tasks_service_last_seen", table_name="studio_task_search_projections")
    op.drop_index(
        "ix_studio_tasks_retention",
        table_name="studio_task_search_projections",
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.drop_index("ix_studio_tasks_correlation", table_name="studio_task_search_projections")
    op.drop_table("studio_task_search_projections")
    op.drop_index("ix_studio_service_search_tags_gin", table_name="studio_service_search_projections")
    op.drop_index("ix_studio_service_search_filters", table_name="studio_service_search_projections")
    op.drop_table("studio_service_search_projections")
    op.drop_index("ix_studio_health_history_retention", table_name="studio_service_health_history")
    op.drop_index("ix_studio_health_history_status_time", table_name="studio_service_health_history")
    op.drop_index("ix_studio_health_history_service_time", table_name="studio_service_health_history")
    op.drop_table("studio_service_health_history")
    op.drop_index("ix_studio_health_current_status", table_name="studio_service_health_current")
    op.drop_table("studio_service_health_current")
    op.drop_table("studio_pull_ingestion_cursors")
    op.drop_index("ix_studio_events_status_stage_time", table_name="studio_events")
    op.drop_index(
        "uq_studio_events_service_source_event_id",
        table_name="studio_events",
        postgresql_where=sa.text("event_id IS NOT NULL"),
    )
    op.drop_index("ix_studio_events_service_time", table_name="studio_events")
    op.drop_index("ix_studio_events_task_effective_time", table_name="studio_events")
    op.drop_index("ix_studio_events_service_effective_time", table_name="studio_events")
    op.drop_index("ix_studio_events_service_task_time", table_name="studio_events")
    op.drop_index(
        "ix_studio_events_retention", table_name="studio_events", postgresql_where=sa.text("expires_at IS NOT NULL")
    )
    op.drop_index("ix_studio_events_correlation_time", table_name="studio_events")
    op.drop_table("studio_events")
    op.drop_index(
        "uq_studio_services_active_environment_base_url",
        table_name="studio_services",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_studio_services_environment_status", table_name="studio_services")
    op.drop_index("ix_studio_services_base_url", table_name="studio_services")
    op.drop_table("studio_services")
    op.drop_table("studio_redis_imports")
    op.drop_index("ix_studio_outbox_delivered_retention", table_name="studio_outbox")
    op.drop_index(
        "ix_studio_outbox_pending", table_name="studio_outbox", postgresql_where=sa.text("delivered_at IS NULL")
    )
    op.drop_table("studio_outbox")
    op.drop_table("studio_operator_settings")
    op.drop_index("ix_studio_audit_time", table_name="studio_operator_audit_log")
    op.drop_index("ix_studio_audit_target_time", table_name="studio_operator_audit_log")
    op.drop_index("ix_studio_audit_action_time", table_name="studio_operator_audit_log")
    op.drop_index("ix_studio_audit_actor_time", table_name="studio_operator_audit_log")
    op.drop_table("studio_operator_audit_log")
    op.drop_index("ix_studio_notification_state_created", table_name="studio_notification_deliveries")
    op.drop_index("ix_studio_notification_retention", table_name="studio_notification_deliveries")
    op.drop_table("studio_notification_deliveries")
    op.drop_table("studio_notification_batches")
    op.drop_index("ix_studio_members_status_role", table_name="studio_members")
    op.drop_index("ix_studio_members_email", table_name="studio_members")
    op.drop_table("studio_members")
    # ### end Alembic commands ###
